server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      timeout: 360000

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    cors:
      allowed-origins: http://example.com, http://another.example.com
      allowed-methods: GET,POST,PUT,DELETE
      allow-credentials: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@dinkdb_medium?TNS_ADMIN=Wallet_DinkDB
    username: team1
    password: Project12345

mybatis:
  type-aliases-package: com.kopo.openbankapiserver.dto
  mapper-locations: classpath:mappers/*.xml



#spring:
#  devtools:
#    livereload:
#      enabled: true

# JDBC null settings
#mybatis.configuration.jdbc-type-for-null: null
